### ISSUE TITLE
Textures have black borders.

### ISSUE THREAD

**Issue by simco50** [boksajak/referencePT#3]
First of all, this project is excellent, very easy to follow and perfectly understandable.

I've been scratching my head about a few things in the rendered image and how I don't see these in my version.
Notice in the screenshot I captured from the application, the area where the texture is supposed to wrap at its border, there is a black edge.
This is mostly noticeable on the carpet in the image but also at all the edges of the tiles on the floor and walls.
![image](https://user-images.githubusercontent.com/9104312/126034776-94ab7d57-0237-499f-89c7-e71f9348b605.png)
Outputting "material.baseColor" of the primary hit reveals that source of the issue is the texture or the sampler.
Viewing this model in my own application and other gLTF viewers, this is not the case.
I believe this issue is caused by the padding of the texture data because of block compression as the texture dimensions are not divisible by 4.

**Comment by jboksansky** [comment]
Thanks for pointing this out - This was a bug occuring because we pad textures to have a size of multiple of 4 (requirement for BC7 compression) but we didn't adjust UVs to point into original texture area. I have now pushed a fix that adjusts UVs and fills added texels with nearest value from the texture, although it's still recommended to use textures with sizes divisible by 4 for best results.
